### PR TITLE
Update expression bodied members

### PR DESCRIPTION
**Pull request by Grepsy**
Please see discussion in #1

### CODE REVIEW

**Comment by Grepsy** [comment]
I'll create a quick sample project to try it out and share, so we can see the effect or all our rules and easily experiment.

**Comment by Grepsy** [comment]
I've played around a bit and I think the defaults make the most sense, and we can use suggestion or warning instead of silent to encourage it.

**Comment by Grepsy** [comment]
Some sample code to play around with.

```
using System;
using System.Collections.Generic;
using System.Linq;

#pragma warning disable CS8321, IDE0032, IDE0051, IDE0062
namespace TheSustainables.CodeStyle {
    public class ExpressionBodiedMembers {
        private readonly List<int> _internalList = new List<int>();

        private int _singleLineAccessor;
        public int SingleLineAccessor {
            get => _singleLineAccessor;
            set => _singleLineAccessor = value;
        }

        public int MultiLineAccessor {
            get {
                var a = 1;
                return a;
            }
        }

        public int MultiLineProperty => Enumerable.Range(0, 10)
                                                  .First();

        public ExpressionBodiedMembers() {
            var a = Enumerable.Range(0, 10).Where(x => x == 5);

            int getFive() {
                return Enumerable.Range(0, 10).First(x => x == 5);
            }
        }

        private int SingleLineFunction() {
            return Math.Max(0, 1);
        }

        // Only use when there are no side-effects. Consider a property instead.
        private int SingleLineFunction2() {
            return Math.Max(0, 1);
        }

        private int MultiLineFunction() {
            var a = 1;
            return Math.Max(0, a);
        }

        public static ExpressionBodiedMembers operator +(ExpressionBodiedMembers a, ExpressionBodiedMembers b) {
            return new ExpressionBodiedMembers();
        }

        public int this[int i] => _internalList[i];

        public int this[double i] {
            get => _internalList[0];
            set => _internalList[0] = value;
        }

        public int this[float i] {
            get => Enumerable.Range(0, 10)
                             .First();
            set => _internalList[0] = value;
        }
    }
}
```

**Comment by mcliment** [comment]
@Grepsy I agree on keeping it as a suggestion instead of silent, just posted the defaults to show that we are close to the standards.

**Comment by RobertvBraam** [comment]
@Grepsy thank you for the nice example, this will make it easier to discuss about it!

**Comment by RobertvBraam** [comment]
I have one suggestion. What do you guys think of putting the single line functions as expression bodied member?

From:
`private int SingleLineFunction() {
     return Math.Max(0, 1);
}`
To:
`private int SingleLineFunction() => Math.Max(0, 1);`

For the rest it's looking good to me 😄.

**Comment by Grepsy** [comment]
I'm not against it, but only for side-effect free functions and when it makes sense for that file. For methods and functions with side-effects I don't like it. And since that's not configurable I think it's safer to keep the default.

```cs
int Calculate() => 1 + 2; // ok

int Redirect() => OtherType.DoIt(); // ok

int Action(int value) => ModifyState(value); // don't like

void DoIt() => _value = 12; // assignment, don't like
```

But to be honest I think if we automatically try to apply these rules or the "single line" rule then classes will have a very mixed structure which I personally find ugly.

To give an example for a class where I think this style _would_ make sense:

```cs
 public static class Vector2Extensions {
        public static Vector2 Normalize(this Vector2 vector) {
            return Vector2.Normalize(vector);
        }

        public static double Dot(this Vector2 left, Vector2 right) {
            return Vector2.Dot(left, right);
        }

        public static Vector2 Multiply(this Vector2 vector, float d) {
            return Vector2.Multiply(vector, d);
        }

        public static double DistanceTo(this Vector2 left, Vector2 right) {
            return Vector2.Distance(left, right);
        }

        public static double DistanceSquared(this Vector2 left, Vector2 right) {
            return Vector2.DistanceSquared(left, right);
        }

        public static Vector2 ToXY(this Vector2 vector) {
            return new Vector2(vector.X, vector.Y);
        }

        public static Vector2d ToXYd(this Vector2 vector) {
            return new Vector2d(vector.X, vector.Y);
        }

        public static Vector2d ToVector2d(this Vector2 vector) {
            return new Vector2d(vector.X, vector.Y);
        }

        public static IEnumerable<Vector3> ToVector3(this IEnumerable<Vector2> vectors, float z) {
            return vectors.Select(p => new Vector3(p, z));
        }

        public static Vector2 Centroid(this IEnumerable<Vector2> vectors) {
            return vectors.Aggregate((a, b) => a + b) * vectors.Count();
        }
    }
```
But in a domain class where most methods operate on the class data I don't think we should mix it just because we can.

**Comment by wim-jan** [comment]
✋ Mostly agree with @Grepsy. 

It's especially nice when replacing a simple method with a return value:

```csharp

public string Foo(string bar) => SayFoo(bar);

**Comment by wim-jan** [comment]
Sorry, wrong button.

**Comment by wim-jan** [comment]
Sorry, wrong button.

**Comment by RobertvBraam** [comment]
Ok, sounds good. So what you are saying is: it's still possible to put it on one line unless you're doing functions with side effects. And therefor we don't enforce it, right?

**Comment by Grepsy** [comment]
Ok, I've made the update based on feedback. basically defaults with suggestions; except for methods which is silent so we can make our own sensible choices (please don't excessively mix the styles in one file). Please approve if you agree so we can finally get this merged.

**Pull request merged**
