### PR TITLE
Added expression body styling rules

### PR DESCRIPTION
**Pull request by RobertvBraam**

### CODE REVIEW

**Comment by Grepsy** [comment]
Hey guys, I'm going to change the review rules for this repo a bit so we get more eyes on these kinds of changes. I think it's important to have a broad consensus before we merge changes to our style rules because it will affect all of our codebases.

To retro-actively comment on the PR: I think it's good to add these rules to the file to solidify our guidelines, but would like to challenge some of the lines:

What's good to note is the following but from the docs:

> The style rules in this section concern the use of expression-bodied members when the logic consists of a single expression.

```
csharp_style_expression_bodied_accessors = when_on_single_line:suggestion -> true:suggestion
csharp_style_expression_bodied_constructors = false:suggestion -> false:silent
csharp_style_expression_bodied_indexers = when_on_single_line:suggestion
csharp_style_expression_bodied_lambdas = when_on_single_line:suggestion -> true:suggestion
csharp_style_expression_bodied_local_functions = when_on_single_line:suggestion -> false:silent
csharp_style_expression_bodied_methods = when_on_single_line:suggestion -> false:silent (this one I find most important b/c I find it confusing to have methods with side-effects be in this style)
csharp_style_expression_bodied_operators = when_on_single_line:suggestion
csharp_style_expression_bodied_properties = true:suggestion
```

I can send another PR for these changes if we all agree.

**Comment by mcliment** [comment]
@Grepsy I agree on your explanation but I think that in general I prefer to put `false:suggestion` or `false:warning` so you offer a hint to solve a bad usage. I don't see what's wrong with that.

As well we should update the Wiki with these rules and decisions.

In any case, rules should always follow current practices (if possible, sometimes there are inconsistencies) unless we really want to change them.

**Comment by Grepsy** [comment]
The ones I put on silent are where I think the developer should make a conscious choice and use some common sense instead of basing it off the warning/suggestions. The problem I have in some cases with suggestions is they seem to get applied _always_ and/or automatically (see last line).

But if most people prefer that way I'm ok; then we can just mention it in our code-style guide and pick it up in reviews.

**Comment by mcliment** [comment]
In fact I think that Rider is more eager to apply all refactorings even if suggested but I'm not sure. In any case if that's the case that a "suggestion" is applied by default I agree that it's better to suppress it.

**Pull request merged**
